### PR TITLE
Chris eda

### PR DESCRIPTION
**Pull request by cwojan**
Bringing in some actual data wrangling / exploration files

### CODE REVIEW

**Comment by Chri3744** [comment]
So just to make sure I'm getting what's here.  This is our website
framework, but your page isn't pushed yet right?  I just want to ask
because I didn't see the files I'd expect your page to be built in.

**Comment by cwojan** [comment]
Yeah, I just merged in my eda files so I can rewrite them to knit to html files that the website will link to, but nothing is built yet. I plan to have phenology pages sometime this evening.

Best,
Chris

**Comment by Chri3744** [comment]
Groovy.  So I'm playing around with leaflet right now, and I'm starting to
wonder if it's not going to pair very well with the domain data.  ggplotly
seems to handle it with no issue, but feeding the data into leaflet is
mostly getting me a blank map or a blank grey field, not sure how to get it
to understand the spatial data.  That  said, judging by the final project
overview, we might not really need to get it into the leaflet, so I might
not worry about it and instead start thinking about getting these plotly
versions playing nice on the website and figuring out what additional text
I might want on the page.

-Taylor

**Comment by Chri3744** [comment]
Also would I be good to push what I have with the basic code for my
question added to the "code" folder?

**Comment by cwojan** [comment]
Yeah, I think you should be fine, so long as its on a different branch. Although it might be fine if its on main as well, but seems riskier. I don’t have much experience with merging haha.

**Comment by Chri3744** [comment]
do you have a branch out right now?  if not I imagine I'm fine merging to
main right?

**Comment by cwojan** [comment]
I do have the “phenology” branch out, but I’m only editing my “mosq_data_download.R” and my .rmd files. So I don’t think there should be any conflicts with you merging in your separate files. Though I suppose we’ll eventually need to use the same data download .R. (I just used it to download everything 2016 to 2020 and it took a really long time btw- ~120 MB).

**Pull request merged**
